# Generated by Django 5.0.7 on 2024-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_tweet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='media',
            field=models.ImageField(upload_to='tweets/', blank=True, null=True),

        ),
    ]
