# Generated by Django 5.0.7 on 2024-07-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_rename_image_tweet_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='tweets/'),
        ),
    ]
